BoxLayout:
    orientation: 'vertical'
#    orientation: 'horizontal'
    Button:
        text: 'one'
    Button:
        text: 'two'
    Button:
        text: 'three'

    # Add a label below the third button with the text "Enter your name":
    # Set the new label's text colour to yellow, by adding the following property details "inside" the label:
    Label:
        text: "Enter your name"
        color: (1, 1, 0, 1)


